# Generated by Django 3.1.7 on 2021-02-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_author_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateTimeField(null=True, verbose_name='Died'),
        ),
    ]
